language: python
python:
    - "3.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio remote -a rpi3bp run
    - platformio remote -a rpi3bp test
